POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "destination": "andresjch2804@gmail.com"
}

###

GET http://localhost:3000/api/auth/login/callback?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXN0aW5hdGlvbiI6ImFuZHJlc2pjaDI4MDRAZ21haWwuY29tIiwiY29kZSI6IjIzMjAwIiwiaWF0IjoxNjkyODk2MDk4LCJleHAiOjE2OTI4OTYzOTh9.erinVP1Bez54pVpcZ2Z1oxqGKVmItGBsTjkrqBeY_DA

> {% client.global.set('access_token', response.body.access_token) %}
